const TourActionTypes = {
  GET_TOUR_LIST_START: 'GET_TOUR_LIST_START',
  GET_TOUR_LIST_SUCCESS: 'GET_TOUR_LIST_SUCCESS',
  GET_TOUR_LIST_FAILURE: 'GET_TOUR_LIST_FAILURE',
};

export default TourActionTypes;
