const DestinationActionTypes = {
  GET_DESTINATION_LIST_START: 'GET_DESTINATION_LIST_START',
  GET_DESTINATION_LIST_SUCCESS: 'GET_DESTINATION_LIST_SUCCESS',
  GET_DESTINATION_LIST_FAILURE: 'GET_DESTINATION_LIST_FAILURE',
};

export default DestinationActionTypes;
