export const DRAWER_MENU_LABEL = {
  DASHBOARD: 'DASHBOARD',
  USERS: 'USERS',
  TOURS: 'TOURS',
  TOUR_ADD: 'TOUR_ADD',
  TOUR_LIST: 'TOUR_LIST',
  INSTOURS: 'INSTOURS',
  INSTOURS_ADD: 'INSTOURS_ADD',
  INSTOURS_LIST: 'INSTOURS_LIST',
};
