export const AuthActionTypes = {
  SIGNIN_REQUEST: 'AUTH/SIGNIN_REQUEST',
  SIGNIN_SUCCESS: 'AUTH/SIGNIN_SUCESS',
  SIGNIN_FAILURE: 'AUTH/SIGNIN_FAILURE',
  SIGNUP_REQUEST: 'AUTH/SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'AUTH/SIGNUP_SUCESS',
  SIGNUP_FAILURE: 'AUTH/SIGNUP_FAILURE',
  SIGNOUT: 'AUTH/SIGNOUT',
  CHECK_USER_SESSION: 'AUTH/CHECK_USER_SESSION',
};

export default AuthActionTypes;
