const TourItemActionTypes = {
  GET_TOUR_ITEM_START: 'GET_TOUR_ITEM_START',
  GET_TOUR_ITEM_SUCCESS: 'GET_TOUR_ITEM_SUCCESS',
  GET_TOUR_ITEM_FAILURE: 'GET_TOUR_ITEM_FAILURE',
  CREATE_TOUR_ITEM_START: 'CREATE_TOUR_ITEM_START',
  CREATE_TOUR_ITEM_SUCCESS: 'CREATE_TOUR_ITEM_SUCCESS',
  CREATE_TOUR_ITEM_FAILURE: 'CREATE_TOUR_ITEM_FAILURE',
};

export default TourItemActionTypes;
